version: '3.8'

services:
  api:
    build:
      context: ./backend/auth-service
    container_name: api-container
    ports:
      - '3000:3000' # Expose the API on port 3000
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    container_name: postgres-container
    ports:
      - '5432:5432' # Expose PostgreSQL on the default port
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data

volumes:
  postgres_data:
